---
title: "Exhaustive Enumeration Results"
output: html_notebook
---

```{r}
library(ggplot2)

# Center plot titles.
theme_update(plot.title = element_text(hjust = 0.5))
```

```{r}
layerParts <- read.csv('layer_parts.csv')
summary(layerParts)
```

```{r}
subset(
  aggregate(num_states ~ layer_sum + max_exponent + board_size, layerParts, sum),
  board_size == 3 & max_exponent == 10)
```

```{r}
plotLayerPartsSummary <- function (layerParts, xBreaks, title = NULL) {
  ggplot(
    transform(
      layerParts,
      max_tile_value = factor(2**max_value)),
    aes(x = layer_sum, y = num_states)) +
    geom_area(aes(fill = max_tile_value)) +
    scale_fill_brewer(name = 'Max Tile Value') +
    scale_x_continuous(breaks = xBreaks) +
    scale_y_continuous(
      labels = function (n) format(n, scientific = FALSE, big.mark = ',')) +
    ggtitle(paste('Number of States by Tile Sum and Max Tile Value', title)) +
    xlab('Sum of Tiles in State') +
    ylab('Number of States')
}
```

```{r}
local({
  g <- plotLayerPartsSummary(
    subset(layerParts, board_size == 3 & max_exponent == 10 & num_states > 0),
    256 * seq(1, 6),
    title = '(3x3 to 1024)'
  )
  svg('enumeration_3x3_to_1024.svg', width = 8, height = 4)
  print(g)
  dev.off()
  g
})
```

```{r}
plotLayerPartsSummary(
  subset(layerParts, board_size == 4 & max_exponent == 6 & num_states > 0),
  32 * seq(1, 11)
)
```

```{r}
subset(layerParts, board_size == 4 & max_exponent == 6)
```

### Partial Build

```{r}
source('../layer_parts.R')
partialParts <- readPartSizes('../layer_check/build-03')
names(partialParts) <- c('file', 'layer_sum', 'max_value', 'num_states')
```

```{r}
summary(partialParts)
```

```{r}
local({
  g <- plotLayerPartsSummary(partialParts, 32 * seq(1, 12), title = '(4x4 incomplete)')
  svg('enumeration_4x4_to_2048_partial.svg', width = 8, height = 4)
  print(g)
  dev.off()
  g
})
```

```{r}
plotLayerPartsLog <- function (layerParts, xBreaks, title = NULL) {
  layerPartsTotal <- aggregate(num_states ~ layer_sum, layerParts, sum)
  print(summary(layerPartsTotal))
  ggplot(
    transform(
      layerParts,
      max_tile_value = factor(2**max_value)),
    aes(x = layer_sum, y = num_states)) +
    geom_line(aes(color = max_tile_value)) +
    geom_line(data = layerPartsTotal) +
    scale_color_brewer(name = 'Max Tile Value') +
    scale_x_continuous(breaks = xBreaks) +
    scale_y_continuous(
      labels = function (n) format(n, scientific = FALSE, big.mark = ','),
      trans = 'log10') +
    ggtitle(paste('Number of States by Tile Sum and Max Tile Value', title)) +
    xlab('Sum of Tiles in State') +
    ylab('Number of States (Log Scale)')
}

```

```{r}
local({
  g <- plotLayerPartsLog(
    subset(partialParts, num_states > 0),
    32 * seq(1, 12),
    title = '(4x4 incomplete)'
  )
  svg('enumeration_4x4_to_2048_partial_log.svg', width = 8, height = 4)
  print(g)
  dev.off()
  g
})
```
